# Generated by Django 3.2.12 on 2022-03-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_feed_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='profile_image',
        ),
    ]
