# Generated by Django 3.2.12 on 2022-03-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_bookmark_like_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='like_count',
        ),
    ]
