# Generated by Django 3.2.12 on 2022-03-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_feed_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='is_markerd',
            new_name='is_marked',
        ),
    ]
